/**
 * IssueReporter - Automatically creates GitHub issues for world problems
 *
 * Agents detect problems (API errors, collision issues, chat failures, etc.)
 * and the orchestrator creates GitHub issues via `gh` CLI.
 */

import { execFileSync } from 'child_process';

export type WorldIssue = {
  agentName: string;
  area: string;
  title: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  evidence: {
    errorCode?: string;
    errorMessage?: string;
    endpoint?: string;
    agentPosition?: { x: number; y: number };
    zone?: string | null;
    timestamp: number;
    context?: string;
  };
};

export class IssueReporter {
  private recentIssues: Set<string> = new Set();
  private enabled: boolean;

  constructor(enabled = true) {
    this.enabled = enabled;
  }

  async reportIssue(issue: WorldIssue): Promise<string | null> {
    const fingerprint = `${issue.area}:${issue.title.slice(0, 40)}`;

    // Dedup within session
    if (this.recentIssues.has(fingerprint)) {
      return null;
    }
    this.recentIssues.add(fingerprint);

    if (!this.enabled) {
      console.log(`[IssueReporter] Would report: ${issue.title}`);
      return null;
    }

    const title = `[Ecosystem][${issue.agentName}] ${issue.title}`;
    const body = this.formatBody(issue);

    try {
      const labels = ['ecosystem-agent', issue.area.toLowerCase(), issue.severity];
      const result = execFileSync(
        'gh',
        ['issue', 'create', '--title', title, '--body', body, '--label', labels.join(',')],
        { encoding: 'utf-8' }
      );

      const issueUrl = result.trim();
      console.log(`[IssueReporter] Created: ${issueUrl}`);
      return issueUrl;
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown';
      console.error(`[IssueReporter] Failed to create issue: ${msg}`);
      return null;
    }
  }

  /** Report API errors detected during agent operation */
  reportApiError(
    agentName: string,
    endpoint: string,
    errorCode: string,
    errorMessage: string,
    position?: { x: number; y: number },
    zone?: string | null
  ): void {
    this.reportIssue({
      agentName,
      area: 'API',
      title: `${endpoint} returns ${errorCode}`,
      description: `Agent ${agentName} encountered an API error while calling ${endpoint}.`,
      severity: errorCode === 'internal' ? 'high' : 'medium',
      evidence: {
        errorCode,
        errorMessage,
        endpoint,
        agentPosition: position,
        zone,
        timestamp: Date.now(),
      },
    }).catch(() => {}); // Fire and forget
  }

  private formatBody(issue: WorldIssue): string {
    const lines: string[] = [
      `## Description`,
      issue.description,
      '',
      `## Evidence`,
      `- **Agent**: ${issue.agentName}`,
      `- **Severity**: ${issue.severity}`,
      `- **Time**: ${new Date(issue.evidence.timestamp).toISOString()}`,
    ];

    if (issue.evidence.endpoint) lines.push(`- **Endpoint**: ${issue.evidence.endpoint}`);
    if (issue.evidence.errorCode) lines.push(`- **Error Code**: ${issue.evidence.errorCode}`);
    if (issue.evidence.errorMessage)
      lines.push(`- **Error Message**: ${issue.evidence.errorMessage}`);
    if (issue.evidence.agentPosition) {
      lines.push(
        `- **Position**: (${issue.evidence.agentPosition.x}, ${issue.evidence.agentPosition.y})`
      );
    }
    if (issue.evidence.zone) lines.push(`- **Zone**: ${issue.evidence.zone}`);
    if (issue.evidence.context) lines.push(`\n### Context\n${issue.evidence.context}`);

    lines.push('');
    lines.push('---');
    lines.push('*Auto-generated by OpenClaw Living Ecosystem*');

    return lines.join('\n');
  }
}
